### ISSUE TITLE
Contact us page

### ISSUE THREAD

**Issue by astha-garhewal** [Girlscript-Chapter-Bilaspur/Official-Website#5]
Design a contact us page using HTML CSS and Bootstrap.

**Comment by smritihalder** [comment]
I want to work with this page

**Comment by astha-garhewal** [comment]
@smritihalder start working

**Comment by smritihalder** [comment]
Done mam!!
[girlscript1.zip](https://github.com/Girlscript-Chapter-Bilaspur/Official-Website/files/5244427/girlscript1.zip)
